sms/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

// admin middleware
Route::group(['middleware'=>['admin']],function(){
	Route::get('home', ['as' => 'home','uses' => 'Admin\HomeController@index']);
	Route::get('home/change_password', ['as' => 'cpassword','uses' => 'Admin\ProfileController@index']);
	Route::post('home/change_password/update', ['as' => 'cpassword','uses' => 'Admin\ProfileController@update']);
	Route::post('home/create_role', ['as' => 'crole','uses' => 'Admin\RegisterController@index']);
	Route::get('home/class/{slug}', ['as' => 'classslug','uses' => 'Admin\SubjectController@index']);

	// to get student of respective class
	Route::get('home/class/student/{class_id}', ['as' => 'getStudent','uses' => 'Admin\StudentController@getStudent']);

	Route::get('home/class/{class}/{sub}', ['as' => 'topicslug','uses' => 'Admin\TopicController@index']);
	Route::get('home/class/{class}/{sub}/{topic}', ['as' => 'subtopicslug','uses' => 'Admin\SubTopicController@index']);
	Route::post('home/student/store', ['as' => 'studentstore','uses' => 'Admin\StudentController@store']);
	Route::get('home/student/{email}', ['as' => 'studentinfo','uses' => 'Admin\StudentController@getStudentInfo']);
	Route::get('home/student/{email}/exam/mark/{exam}', ['as' => 'studentinfoexammark','uses' => 'Admin\StudentController@getStudentExamInfo']);
	Route::get('home/student/{email}/exam/grade/{exam}', ['as' => 'studentinfoexamgrade','uses' => 'Admin\StudentController@getStudentGradeInfo']);
	Route::get('home/student/{email}/fee/{fee}', ['as' => 'studentinfofee','uses' => 'Admin\StudentController@getStudentFeeInfo']);
	Route::post('home/teacher/store', ['as' => 'teacherstore','uses' => 'Admin\TeacherController@store']);

	//for admin->class
	Route::resource('home/class','Admin\ClassController');
	Route::post('home/class/delete', ['as' => 'dcategory','uses' => 'Admin\ClassController@delete']);
	Route::get('home/tclass/edit/{id}', ['as' => 'eclass','uses' => 'Admin\ClassController@edit']);
	Route::post('home/class/update', ['as' => 'uclass','uses' => 'Admin\ClassController@update']);
	Route::resource('home/class_export','Admin\ClassController@export');

	//for admin->student
	Route::resource('home/student','Admin\StudentController');
	Route::resource('home/student_export','Admin\StudentController@export');
	Route::get('home/student_record','Admin\StudentController@student_record');
	Route::post('home/student/delete', ['as' => 'dstudent','uses' => 'Admin\StudentController@delete']);
	Route::get('home/student/edit/{id}', ['as' => 'estudent','uses' => 'Admin\StudentController@edit']);
	Route::post('home/student/update', ['as' => 'ustudent','uses' => 'Admin\StudentController@update']);

	//for shift
	Route::resource('home/shift','Admin\ShiftController');
	Route::post('home/shift/delete', ['as' => 'dshift','uses' => 'Admin\ShiftController@delete']);
	Route::get('home/shift/edit/{id}', ['as' => 'eshift','uses' => 'Admin\ShiftController@edit']);
	Route::post('home/shift/update', ['as' => 'ushift','uses' => 'Admin\ShiftController@update']);
	Route::get('home/shift_export','Admin\ShiftController@export');

	//for section
	Route::resource('home/section','Admin\SectionController');
	Route::post('home/sec/delete', ['as' => 'dcategory','uses' => 'Admin\SectionController@delete']);
	Route::get('home/section/edit/{id}', ['as' => 'esection','uses' => 'Admin\SectionController@edit']);
	Route::post('home/section/update', ['as' => 'usection','uses' => 'Admin\SectionController@update']);
	Route::get('home/section_export','Admin\SectionController@export');

	//for admin->subject
	Route::resource('home/subject','Admin\SubjectController');
	Route::post('home/class/subject/delete', ['as' => 'dsubject','uses' => 'Admin\SubjectController@delete']);
	Route::get('home/class/subject/esub/edit/{id}', ['as' => 'esubject','uses' => 'Admin\SubjectController@edit']);
	Route::post('home/subject/update', ['as' => 'usubject','uses' => 'Admin\SubjectController@update']);
	Route::get('home/subject_export','Admin\SubjectController@export');

	// for teacher
	Route::resource('home/teacher','Admin\TeacherController');
	Route::get('home/teacher_export','Admin\TeacherController@export');
	Route::post('home/teacher/delete', ['as' => 'dteacher','uses' => 'Admin\TeacherController@delete']);
	Route::get('home/teacher/edit/{id}', ['as' => 'eteacher','uses' => 'Admin\TeacherController@edit']);
	Route::post('home/teacher/update', ['as' => 'uteacher','uses' => 'Admin\TeacherController@update']);

	// for period
	Route::resource('home/period','Admin\PeriodController');
	Route::post('home/period/delete', ['as' => 'dcategory','uses' => 'Admin\PeriodController@delete']);
	Route::get('home/period_export','Admin\PeriodController@export');
	Route::get('home/period/edit/{id}', ['as' => 'eperiod','uses' => 'Admin\PeriodController@edit']);
	Route::post('home/period/update', ['as' => 'uperiod','uses' => 'Admin\PeriodController@update']);

	// for topic
	Route::resource('home/topic','Admin\TopicController');
	Route::post('home/class/{id}/topic/delete', ['as' => 'dtopic','uses' => 'Admin\TopicController@delete']);
	Route::get('home/class/{cid}/topic/edit/{id}', ['as' => 'etopic','uses' => 'Admin\TopicController@edit']);
	Route::post('home/topic/update', ['as' => 'uteacher','uses' => 'Admin\TopicController@update']);


	//for admin->subtopic
	Route::resource('home/sub_topic','Admin\SubTopicController');
	Route::post('home/class/{id}/{class_id}/subtopic/delete', ['as' => 'dsubject','uses' => 'Admin\SubTopicController@delete']);
	Route::get('home/class/{cid}/{class_id}/subtopic/edit/{id}', ['as' => 'esubtopic','uses' => 'Admin\SubTopicController@edit']);
	Route::post('home/subtopic/update', ['as' => 'usub_topic','uses' => 'Admin\SubTopicController@update']);
	Route::get('home/sub_topic_export','Admin\SubTopicController@export');

	//Teacher record
	Route::get('home/daily-teacher-record', ['as' => 'teacherstore','uses' => 'Admin\TeacherRecordController@index']);
	Route::get('home/getSubject/{teacher_id}', ['as' => 'gsubjectrecord', 'uses' => 'Admin\TeacherRecordController@getTeacherClass']);
	Route::get('home/getClass/{subject_id}', ['as' => 'gsubjectrecord', 'uses' => 'Admin\TeacherRecordController@getSubjectClass']);
	Route::get('home/getTopic/{subject_id}', ['as' => 'gsubjectrecord', 'uses' => 'Admin\TeacherRecordController@getSubjectTopic']);
	Route::get('home/getSubTopic/{topic_id}', ['as' => 'gsubjectrecord', 'uses' => 'Admin\TeacherRecordController@getSubjectSubTopic']);
	Route::get('home/getSection/{class_id}', ['as' => 'gsectionrecord', 'uses' => 'Admin\TeacherRecordController@getSection']);
	Route::get('home/getShift/{class_id}', ['as' => 'gsectionrecord', 'uses' => 'Admin\TeacherRecordController@getShift']);
	Route::post('home/daily-teacher-record/store', ['as' => 'teacherstore','uses' => 'Admin\TeacherRecordController@store']);
	Route::get('home/daily_teacher_record/view', ['as' => 'teacherstore','uses' => 'Admin\TeacherRecordViewController@index']);
	Route::get('home/daily_teacher_record/teacher_search', ['as' => 'teachersearch','uses' => 'Admin\TeacherRecordViewController@teacher_search']);
	
	// route to get shift and section on student
	Route::get('home/getSectionOnStudent/{class_id}', ['as' => 'gsectionrecord', 'uses' => 'Admin\StudentController@getSectionOnStudent']);
	Route::get('home/getShiftOnStudent/{class_id}', ['as' => 'gsectionrecord', 'uses' => 'Admin\StudentController@getShiftOnStudent']);
	Route::get('home/getSubjectOnStudent/{class_id}', ['as' => 'gsubjectrecord', 'uses' => 'Admin\StudentController@getSubjectOnStudent']);

	//Exam control
	Route::get('home/exam', ['as' => 'examindex','uses' => 'Admin\ExamController@index']);
	Route::post('home/exam/delete', ['as' => 'dexam','uses' => 'Admin\ExamController@delete']);
	Route::get('home/exam/edit/{id}', ['as' => 'eexam','uses' => 'Admin\ExamController@edit']);
	Route::get('home/exam_export', ['as' => 'examexport','uses' => 'Admin\ExamController@export']);
	Route::post('home/exam/store', ['as' => 'examstore','uses' => 'Admin\ExamController@store']);
	Route::post('home/exam/update', ['as' => 'examstore','uses' => 'Admin\ExamController@update']);
	Route::get('home/exam/exam_search', ['as' => 'examsearch','uses' => 'Admin\ExamController@exam_search']);

	Route::get('home/exam-detail/view', ['as' => 'examdetailview','uses' => 'Admin\ExamController@examdetail']);
	Route::get('home/exam-detail/view/mark/{exam}/{roll}', ['as' => 'examdetailview','uses' => 'Admin\ExamController@examdetailStudent']);
	Route::get('home/exam-detail/view/grade/{exam}/{roll}', ['as' => 'examdetailview','uses' => 'Admin\ExamController@gradedetailStudent']);
	Route::post('home/exam-detail/marksheet/unpublish', ['as' => 'examdetailview','uses' => 'Admin\ExamController@unpublish']);
	Route::post('home/exam-detail/getStudentMarkStudent', ['as' => 'examdetailview','uses' => 'Admin\ExamController@getStudentMarkStudent']);

	//Exam and class subjects
	Route::get('home/exam/{exam_id}/class/{class_id}', ['as' => 'examclassindex','uses' => 'Admin\ExamClassController@index']);
	Route::post('home/exam/class/store', ['as' => 'examclassindex','uses' => 'Admin\ExamClassController@store']);
	Route::post('home/exam/class/update', ['as' => 'examclassindex','uses' => 'Admin\ExamClassController@update']);

	// get all value after exam click
	Route::get('home/exam/{exam_id}', ['as' => 'exammarkindex','uses' => 'Admin\ExamMarkController@index']);
	Route::get('home/exam/getSectionOnStudent/{class_id}', ['as' => 'gsectionrecord', 'uses' => 'Admin\ExamMarkController@getSectionOnStudent']);

sms/resources/views/admin/attendance_ajax.blade.php
<form class="general-form" method="POST" action="{{URL::to('/')}}/home/daily-student-attendance/store">
<input type="hidden" name="_token" class="token" value="{{ csrf_token() }}">
<div id="printDiv">
  Date:{{$attendance_date}} | Class: {{$class_name['0']['name']}} | Section: {{$section_name['0']['name']}} | Shift: {{$shift_name['0']['name']}} 
<table class="table table-bordered">
  <thead> 
    <tr>
        <th>SN</th>
        <th>Name</th>
        <th>Attendance</th>
        <th>Remark</th>
    </tr>
  </thead>
  <tbody>
        @if(count($class_attendance))
          @foreach($class_attendance as $index=>$student_list)
          <tr>
           <td>{{$index+1}}</td>
           <td>{{$student_list->getStudent->name}}</td>
           <input type="hidden" name="student_id[]" value="{{$student_list->getStudent->id}}">
           <input type="hidden" name="class_id[]" value="{{$class_id}}">
           <input type="hidden" name="shift_id[]" value="{{$shift_id}}">
           <input type="hidden" name="section_id[]" value="{{$section_id}}">
           <td>
              {{$student_list->title}}
            </td>
            <td>{{$message}}</td>
          </tr>
          @endforeach
        @endif
        
        @if(count($student_lists))
        @foreach($student_lists as $index=>$student_list)
    <tr>
     <td>{{$index+1}}</td>
     <td>{{$student_list->studentinfo->name}}</td>
     <input type="hidden" name="student_id[]" value="{{$student_list->studentinfo->id}}">
     <input type="hidden" name="class_id[]" value="{{$class_id}}">
     <input type="hidden" name="shift_id[]" value="{{$shift_id}}">
     <input type="hidden" name="section_id[]" value="{{$section_id}}">
     <td>
        <input type="radio" id="present.{{$student_list->studentinfo->id}}" name="attendance[].{{$student_list->studentinfo->id}}" value="Present"  checked>
          <label class="control-label" for="present.{{$student_list->studentinfo->id}}">Present</label> | 
        <input type="radio" id="absent.{{$student_list->studentinfo->id}}" name="attendance[].{{$student_list->studentinfo->id}}" value="Absent">
          <label class="control-label" for="absent.{{$student_list->studentinfo->id}}">Absent</label>
      </td>
      <td>{{$message}}</td>
    </tr>
      @endforeach
  </tbody>
</table>
</div>
@if(!$btndis)
  <div class="text-center">
    <button type="submit" class="btn btn-default btn-sm">
      Make Attendance<i class="fa fa-paper-plane-o"></i>
    </button>
  </div>
  @else
<button type="button" class="btn btn-default btn-sm" onclick="PrintDiv('printDiv')" >PRINT<i class="fa fa-print"></i></button>
@endif
        @endif

      
</form>

sms/resources/views/admin/event_add_ajax.blade.php
<table class="table table-bordered">
  <thead> 
    <tr>
        <th>SN</th>
        <th>Title</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Created By</th>
        <th>Created On</th>
        <th class="hidden-print">Action</th>
    </tr>
  </thead>
  <tbody>
      @foreach($calendars as $index=>$calendar)
    <tr>
     <td>{{$index+1}}</td>
     <td>{{$calendar->title}}</td>
     <td>{{$calendar->start}}</td>
     <td>{{$calendar->end}}</td>
     <td>{{$calendar->getUser->name}}</td>
     <td>{{$calendar->created_at}}</td>
     <td class="hidden-print">
      <a class="action-btn edit" id="calendar" data-target="#edit_calendar" data-toggle="modal" href=""><i class="fa fa-pencil-square-o" id="{{$calendar->id}}"></i></a>
      <a class="action-btn bg-green delete" id="calendar" href="javascript:void(0)"><i class="fa fa-times" id="{{$calendar->id}}"></i></a>
     </td>
    </tr>
      @endforeach
  </tbody>
</table>

sms/resources/views/admin/grade_export.blade.php
<?php
// We change the headers of the page so that the browser will know what sort of file is dealing with. Also, we will tell the browser it has to treat the file as an attachment which cannot be cached.
 
//header("Content-type: application/octet-stream;charset=utf-8");
header("Content-Type: text/html; charset=UTF-8");
header("Content-Disposition: attachment; filename=GradeRecord.xls");
header("Pragma: no-cache");
header("Expires: 0");
?>
<table class="table table-bordered" border="1">
    <thead> 
        <tr>
            <th>SN</th>
            <th>Grade</th>
            <th>From</th>
            <th>To</th>
    </thead>
    <tbody>
        @foreach($grades as $index=>$grade)
        <tr>
           <td>{{$index+1}}</td>
           <td>{{$grade->name}}</a></td>
           <td>{{$grade->lower}}</td>
           <td>{{$grade->higher}}</td>
        </tr>
        @endforeach
    </tbody>
  </table>

sms/resources/views/admin/help.blade.php
@extends('admin.app')

@section('content')
@include('admin.sidebar')
<div class="admin-content">
	<div class="admin-top">
	<div class="flash-message">
		@foreach (['danger', 'warning', 'success', 'info'] as $msg)
		    @if(Session::has('alert-' . $msg))
		<p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
		  @endif
		@endforeach
	</div>
		@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Whoops!</strong> There were some problems with your input.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
						<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
		@endif
	</div>
  @foreach($user_levels as $userlevel)
  @if(($userlevel->getUserLevel->user_level == '1')||($userlevel->getUserLevel->user_level == '2'))
	<div class="heading"><h2>Help Summary</h2></div>
    <div class="row">
    <div class="col-md-8">
      <table class="table table-bordered">
        <thead> 
          <tr>
              <th>Help</th>
          </tr>
        </thead>
        <tbody>
          @foreach($helps as $index=>$help)
            <tr>
               <td>{!! $help->name !!}</td>
            </tr>
          @endforeach 
        </tbody>
      </table>
    </div>
    </div>
    @else
    <div class="heading"><h2>You have no right access</h2></div>
    @endif
    @endforeach
</div>
@endsection

sms/resources/views/admin/role_export.blade.php
<?php
// We change the headers of the page so that the browser will know what sort of file is dealing with. Also, we will tell the browser it has to treat the file as an attachment which cannot be cached.
 
//header("Content-type: application/octet-stream;charset=utf-8");
header("Content-Type: text/html; charset=UTF-8");
header("Content-Disposition: attachment; filename=RoleRecord.xls");
header("Pragma: no-cache");
header("Expires: 0");
?>
<table class="table table-bordered" border="1">
    <thead> 
      <tr>
          <th>SN</th>
          <th>Full Name</th>
          <th>Address</th>
          <th>Email</th>
          <th>DOB</th>
          <th>Gender</th>
          <th>T No</th>
          <th>M No</th>
          <th>User Level</th>
    </thead>
    <tbody>
        @foreach($roles as $index=>$role)
        <tr>
       <td>{{$index+1}}</td>
       <td>{{$role->name}}</td>
       <td>{{$role->address}}</td>
       <td>{{$role->email}}</td>
       <td>{{$role->dob}}</td>
       <td>{{$role->gender}}</td>
       <td>{{$role->telephone_no}}</td>
       <td>{{$role->mobile_no}}</td>
       <td>{{$role->getUserLevel->title}}</td>
        </tr>
        @endforeach
    </tbody>
  </table>

sms/resources/views/admin/section_export.blade.php
<?php
// We change the headers of the page so that the browser will know what sort of file is dealing with. Also, we will tell the browser it has to treat the file as an attachment which cannot be cached.
 
//header("Content-type: application/octet-stream;charset=utf-8");
header("Content-Type: text/html; charset=UTF-8");
header("Content-Disposition: attachment; filename=SectionRecord.xls");
header("Pragma: no-cache");
header("Expires: 0");
?>
<table class="table table-bordered" border="1">
    <thead> 
      <tr>
          <th>SN</th>
          <th>Section</th>
      </tr>
    </thead>
    <tbody>
        @foreach($sections as $index=>$sec)
          <tr>
             <td>{{$index+1}}</td>
             <td>{{$sec->name}}</td>
         </tr>
        @endforeach
    </tbody>
  </table>

sms/resources/views/admin/student_exam_detail_grade.blade.php
@extends('admin.app')
@section('content')
@include('admin.sidebar')
<div class="admin-content">
	<div class="admin-top">
	<div class="flash-message">
		@foreach (['danger', 'warning', 'success', 'info'] as $msg)
		    @if(Session::has('alert-' . $msg))
		<p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
		  @endif
		@endforeach
	</div>
		@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Whoops!</strong> There were some problems with your input.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
						<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
		@endif
	</div>
  @foreach($user_levels as $userlevel)
  @if(($userlevel->getUserLevel->user_level == '1')||($userlevel->getUserLevel->user_level == '3'))
	<div class="heading"><h2>Marksheet Summary</h2></div>
  @if(count($studentmarksheets))
	 <div class="row">
  <div class="col-md-8">
     <div id="printDiv">
    <p>Student Name: <b>{{$student_name}}</b><span class="pull-right"> Class:{{$class_name}}</span></p>
     <p>Section:{{$class_section}} <span class="pull-right">Shift:{{$class_shift}}</span></p>
     <p><span class="pull-center">Exam: {{$exam_name}}</span></p>
    <table class="table table-bordered" >
    <thead> 
      <tr>
          <th>SN</th>
          <th>Subject</th>
          <th>Grade</th>
      </tr>
    </thead>
    <div class="watermark">{{$message}}</div>
    @foreach($studentmarksheets as $index=>$studentmarksheet)
          <tr>
             <td>{{$index+1}}</td>
              @foreach($studentmarksheet->getStudentSubMark()->get() as $studentmark)
             <td>
                  {{$studentmark->getSubjectClass->name}}
             </td>
              @endforeach
              @foreach($studentmarksheet->getStudentGrade()->get() as $sub_grade)
              <td>{{$sub_grade->getStudentMarkGrade->name}}</td>
              @endforeach
            </tr>

    @endforeach
  </table>
</div>
  <div class="row">
    <div class="col-md-12 text-right container-pd">
      <button onclick="PrintDiv('printDiv')" id="print" class="btn btn-default btn-sm">Print</button>
    </div>              
  </div>
  </div>
  </div>
  @else
    <div class=""><h2>Please upload marksheet</h2></div>
  @endif
  @else
  <div class="heading"><h2>You have no right access</h2></div>
  @endif
  @endforeach
</div>
@endsection

sms/resources/views/admin/sub_topic.blade.php
@extends('admin.app')
@section('content')
@include('admin.sidebar')
<div class="admin-content">
  <div class="admin-top">
  <div class="flash-message">
    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
        @if(Session::has('alert-' . $msg))
    <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
      @endif
    @endforeach
  </div>
    @if (count($errors) > 0)
      <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
          @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
    @endif
  </div>
  @foreach($user_levels as $userlevel)
  @if(($userlevel->getUserLevel->user_level == '1')||($userlevel->getUserLevel->user_level == '2'))
  <div class="heading"><h2>{{$subtopic_name}} Topic Summary</h2></div>
  <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#mysubTopic">
      Add Sub Topic on {{$subtopic_name}}
    </button> 
  <div class="col-md-12">
    <div class="row">
    <table class="table table-bordered">
    <thead> 
        <tr>
         <th>SN</th>
          <th>Sub Topic Name</th>
          <th>Sub Topic hour</th>
          <th class="hidden-print">Action</th>
    </tr>
    </thead>
    <tbody>
        @foreach($subtopics as $index=>$subtopic)
        <tr>
         <td>{{$index+1}}</td>
         <td>{{$subtopic->name}}</td>
         <td>{{$subtopic->subtopic_hour}}</td>
         <td class="hidden-print">
          <a class="action-btn edit" id="subtopic" data-target="#edit_subtopic" data-toggle="modal" href=""><i class="fa fa-pencil-square-o" id="{{$subtopic->id}}"></i></a>
            <a class="action-btn bg-green delete" id="subtopic" href="javascript:void(0)"><i class="fa fa-times" id="{{$subtopic->id}}"></i></a>
            </tr>
      </tr>
        @endforeach
    </tbody>
    </table>
      </div>
    </div>
    </div>
    <div id="mysubTopic" class="modal fade admin-model" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
      <div class="modal-content">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <div class="modal-body">
    <div class="form-holder">
      <div class="row">
        <div class="col-xs-12 form-box">
        <form class="general-form add-category" id="subtopic_valid" action="{{URL::route('home.sub_topic.store')}}"  method="POST" enctype="multipart/form-data">
        <input type="hidden" name="_token" class="token" value="{{ csrf_token() }}">
        <input type="hidden" name="topic_id" value="{{$subtopic_id}}">
        <h2>Add Sub Topic on {{$subtopic_name}}</h2>
        <p class="add-info">* Denotes required Field</p>
        <div class="row">
          <label for="subtopic_name" class="col-md-4 control-label">Sub Topic Name:</label>
            <div class="col-md-8">
            <div class="form-group">
            <div class="required">
            <input type="text" class="form-control input-sm" id="subtopic_name" name="name" placeholder="Please enter sub topic name">
            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <label for="subtopic_hour" class="col-md-4 control-label">Sub Topic Hour:</label>
            <div class="col-md-8">
            <div class="form-group">
            <div class="required">
            <input type="text" class="form-control input-sm" id="subtopic_hour" name="subtopic_hour" placeholder="Please enter sub topic hour ">
            </div>
            </div>
          </div>
        </div>
        <div class="text-center">
          <button type="submit" class="btn btn-default btn-sm">
            Add Sub Topic<i class="fa fa-paper-plane-o"></i>
          </button>
        </div>
        </form>
        </div>
      </div>
    </div>
    </div>
    <div class="modal-footer">
    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
    </div>
    </div>
    </div>
    </div>

    <div id="edit_subtopic" class="modal fade admin-model" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
      <div class="modal-content">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <div class="modal-body">
    <div class="form-holder">
      <div class="row">
        <div class="col-xs-12 form-box">
        <form class="general-form edit-form" id="subtopic_valid" action="{{ URL::to('/') }}/home/subtopic/update"  method="POST" enctype="multipart/form-data">
        <input type="hidden" name="_token" class="token" value="{{ csrf_token() }}">
        <input type="hidden" name="subtopic_id" class="id">
        

        <h2>Update Sub Topic on {{$subtopic_name}}</h2>
        <p class="add-info">* Denotes required Field</p>
        <div class="row">
          <label for="subtopic_name" class="col-md-4 control-label">Sub Topic Name:</label>
            <div class="col-md-8">
            <div class="form-group">
            <div class="required">
            <input type="text" class="form-control input-sm name" id="subtopic_name" name="name" placeholder="Please enter sub topic name">
            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <label for="subtopic_hour" class="col-md-4 control-label">Sub Topic Hour:</label>
            <div class="col-md-8">
            <div class="form-group">
            <div class="required">
            <input type="text" class="form-control input-sm subtopic_hour" id="subtopic_hour" name="subtopic_hour" placeholder="Please enter sub topic hour ">
            </div>
            </div>
          </div>
        </div>
        <div class="text-center">
          <button type="submit" class="btn btn-default btn-sm">
            Update Sub Topic<i class="fa fa-paper-plane-o"></i>
          </button>
        </div>
        </form>
        </div>
      </div>
    </div>
    </div>
    <div class="modal-footer">
    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
    </div>
    </div>
    </div>
    </div>

   @else
    <div class="heading"><h2>You have no right access</h2></div>
    @endif
    @endforeach
  </div>

  
@endsection